### ISSUE TITLE
We've found duplicated index name across public schema. Please rename your index in either the stations table or the table with the duplicated index name

### ISSUE THREAD

**Issue by primozs** [drizzle-team/drizzle-kit-mirror#275]
migrating drizzle-kit from 0.20.6 somehow missing in release tags, to 0.20.9
issue start from 0.20.7
I cant add any index.

```
export const stations = pgTable(
  'stations',
  {
    id: varchar('id', { length: 256 }).notNull().primaryKey(),
    sourceId: varchar('source_id', { length: 256 }).notNull(),
    name: varchar('name', { length: 256 }).notNull(),
    type: varchar('type', { length: 10 }).notNull(),
    source: varchar('source', { length: 256 }).notNull(),
    webcam: varchar('webcam', { length: 256 }),
    country: varchar('country', { length: 256 }),
    region: varchar('region', { length: 256 }),
    timezone: varchar('timezone', { length: 256 }),
    lat: real('lat'),
    lon: real('lon'),
    elev: integer('elev'),
    url: varchar('url', { length: 256 })
  },
  (t) => {
    return {
      // idIndex: index('id_idx').on(t.id),
      // nameIndex: index('name_idx').on(t.name),
      // typeIndex: index('type_idx').on(t.type),
      sourceIndex: index('source_idx').on(t.source)
    }
  }
)
```

generate allways fails with: 
We've found duplicated index name across public schema. Please rename your index in either the stations table or the table with the duplicated index name

Error is wrong ans misleading, since all other tables are commented out.
Downgrading to 0.20.6 works

**Comment by AndriiSherman** [comment]
I'll check this one. So you have only 1 table and hitting this error?

**Comment by primozs** [comment]
Sorry I should have added this info before.

![Screenshot from 2024-01-02 19-20-21](https://github.com/drizzle-team/drizzle-kit-mirror/assets/1006789/9c5e4506-03ff-437a-b24b-6feab71a070b)

**Comment by Amorim33** [comment]
Same problem here

**Comment by AndriiSherman** [comment]
Can you share your drizzle schema, so I can debug it. You can send me a part of it, but I need to be able to reproduce this issue

**Comment by Amorim33** [comment]
### Schema
```ts
export const insuredItems = pgTable(
  'insured_items',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id),
    policyId: uuid('policy_id')
      .notNull()
      .references(() => policies.id),
    monthlyInsuredItemId: uuid('monthly_insured_item_id')
      .notNull()
      .references(() => monthlyInsuredItems.id),
    insuredPersonId: uuid('insured_person_id')
      .notNull()
      .references(() => insuredPersons.id),
    currentInstallment: integer('current_installment').notNull(),
    installmentAmount: integer('installment_amount').notNull(),
    externalId: varchar('external_id', { length: 50 }).notNull(),
    additionalAttributes: jsonb('additional_attributes'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  (table) => ({
    monthlyInsuredItemExternalIdx: uniqueIndex(
      'monthly_insured_item_external_idx',
    ).on(table.monthlyInsuredItemId, table.externalId),
  }),
);
```

### Error
```
We've found duplicated index name across public schema. Please rename your index in either the insured_items table or the table with the duplicated index name
```

I believe that `push` is trying to recreate the unique index that already exists.
It used to not happen in the previous versions.

**Comment by marbemac** [comment]
Ditto, also confirmed introduced in `0.20.7`.

**Comment by mitchellwarr** [comment]
Having the same issue. It would be helpful for the error message to list out the name of the index its trying to create

**Comment by AndriiSherman** [comment]
Should be fixed in `drizzle-kit@beta`. Could you please approve if it fixed for you , so I can close this issue and release to latest?

**Comment by AndriiSherman** [comment]
Just released to `drizzle-kit@0.20.12`. Will close this issue after a few approves

**Comment by rahmat-dev** [comment]
@AndriiSherman I've installed 0.20.12 version, but still got the same error
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/40190205/ebee5ee2-b169-46bb-ae36-61f9f3e49741)

**Comment by abury** [comment]
Yeah we're still seeing this, it's caused us to hit an absolute brick wall.

drizzle-kit: v0.20.13
drizzle-orm: v0.29.3

We've tried renaming all index's so that they aren't duplicated, but no dice, no matter what we do it comes back with this error message. Will have to downgrade sadly.
